version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: todolist-mongodb-prod
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: todolist
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - todolist-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: todolist-backend-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/todolist?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
    depends_on:
      - mongodb
    networks:
      - todolist-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        API_URL: http://localhost:3000
    container_name: todolist-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - todolist-network

networks:
  todolist-network:
    driver: bridge

volumes:
  mongodb_data:
